// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/win-win/Support.tsx": () => import("../components/mockups/win-win/Support.tsx"),
  "./components/mockups/win-win/UltraPlans.tsx": () => import("../components/mockups/win-win/UltraPlans.tsx")
};
